FROM knime3/base
MAINTAINER Brian Muchmore "brian.muchmore@genyo.es"
 
RUN apt-get update -y && \

##Install LinearTimeNeRV
    apt-get install libncurses5-dev libncursesw5-dev -y && \
    wget http://research.cs.aalto.fi/pml/software/LinearTimeNeRV/linearnerv-0.9.0.tar.gz -O /tmp/lineartimenerv.tar.gz -q && \
    echo 'Installing lineartimenerv' && \
    tar -xf /tmp/lineartimenerv.tar.gz -C /home/developer && \
    rm /tmp/lineartimenerv.tar.gz -rf && \
    cd /home/developer/lineartimenerv && \
    make linearnerv && \   
    wget https://github.com/RGLab/ggcyto/archive/trunk.zip -O /tmp/ggcyto -q && \
    unzip /tmp/ggcyto && \
    echo 'install.packages("/tmp/ggcyto-trunk", repos = NULL, dependencies = TRUE)' >> /home/developer/packages2.R && \

##Run the R packages install script
    Rscript /home/developer/packages2.R && \

##Remove manually downloaded R package(s)
    rm /tmp/NetPreProc_1.0.tar.gz && \
    rm /tmp/ggcyto && \

##Install H2O
    wget http://h2o-release.s3.amazonaws.com/h2o/rel-slater/5/h2o-3.2.0.5.zip -O /tmp/h2o.zip -q && \
    echo 'Installing H2O' && \
    unzip -o /tmp/h2o.zip -d /home/developer && \
    rm -rf /tmp/h2o.zip && \

##Install flowiQC. Downloading does not always work, so unzip was throwing an error. Unzipping with jar seems to yield no error even for a corrupted file.
    wget https://github.com/SIgNBioinfo/flowiQC_shinyAPP/archive/master.zip -O /home/developer/flowiQC.zip -q && \
    jar -xvf /home/developer/flowiQC.zip && \
    rm -rf /home/developer/flowiQC.zip && \

##Install MSSQL database connector
   wget http://www.java2s.com/Code/JarDownload/sqljdbc4/sqljdbc4-3.0.jar.zip -O /home/developer/sqljdbc4.jar.zip -q && \
   jar -xvf /home/developer/sqljdbc4.jar.zip && \
   rm -rf /home/developer/sqljdbc4.jar.zip && \

##Install Python 3.4 and PhenoGraph
    wget https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tar.xz -O /home/developer/Python-3.4.3.tar.xz -q && \
    cd /home/developer && tar xJf /home/developer/Python-3.4.3.tar.xz && \
    rm -rf /home/developer/Python-3.4.3.tar.xz && \
    cd /home/developer/Python-3.4.3 && ./configure --prefix=/opt/python3.4 && make && make install && \
    apt-get install python3-dev -y && \
    /opt/python3.4/bin/pip3 install numpy && \
    /opt/python3.4/bin/pip3 install scipy && \
    /opt/python3.4/bin/pip3 install scikit-learn && \
    /opt/python3.4/bin/pip3 install ipython && \
    /opt/python3.4/bin/pip3 install pyzmq && \
    /opt/python3.4/bin/pip3 install ipyparallel && \
    /opt/python3.4/bin/pip3 install networkx && \
    wget https://github.com/jacoblevine/PhenoGraph/archive/master.zip -O /home/developer/PhenoGraph.zip -q && \
    unzip -o /home/developer/PhenoGraph.zip -d /home/developer && \
    rm -rf /home/developer/PhenoGraph.zip && \
    cd /home/developer/PhenoGraph-master && /opt/python3.4/bin/python3 setup.py install && \
    mv /home/developer/PhenoGraph-master/phenograph/louvain/linux-hierarchy /opt/python3.4/lib/python3.4/site-packages/PhenoGraph-1.2-py3.4.egg/phenograph/louvain/linux-hierarchy && \
    mv /home/developer/PhenoGraph-master/phenograph/louvain/linux-community /opt/python3.4/lib/python3.4/site-packages/PhenoGraph-1.2-py3.4.egg/phenograph/louvain/linux-community && \
    mv /home/developer/PhenoGraph-master/phenograph/louvain/linux-convert /opt/python3.4/lib/python3.4/site-packages/PhenoGraph-1.2-py3.4.egg/phenograph/louvain/linux-convert && \

##Install Combo
    mkdir -p /home/developer/Combo && \
    wget http://senseable.mit.edu/community_detection/combo.zip -O /tmp/combo.zip -q && \
    unzip -o /tmp/combo.zip -d /home/developer/Combo && \
    rm -rf /tmp/combo.zip && \
    echo '#!/bin/bash' > /home/developer/prepend.sh && \
    echo 'content=$(cat /home/developer/Combo/Graph.h)' >> /home/developer/prepend.sh && \
    echo 'echo -en "#include <stdio.h>\n$content" > /home/developer/Combo/Graph.h' >> /home/developer/prepend.sh && \
    chmod 777 /home/developer/prepend.sh && \ 
    /home/developer/prepend.sh && \
    cd /home/developer/Combo && make && \

##Install SNAP
    wget https://github.com/snap-stanford/snap/archive/master.zip -O /tmp/snap.zip -q && \
    unzip -o /tmp/snap.zip -d /home/developer/snap && \
    rm -rf /tmp/snap.zip && \
    cd /home/developer/snap/snap-master && make all

##Install RapidMiner --- SOURCEFORGE LINK BROKEN!!!
##    wget http://sourceforge.net/projects/rapidminer/files/1.%20RapidMiner/5.3/rapidminer-5.3.013.zip/download -O /tmp/RapidMiner.zip -q && \
##    echo 'Installing RapidMiner' && \
##    unzip -o /tmp/RapidMiner.zip -d /home/developer && \
##    rm -rf /tmp/RapidMiner.zip && \


