##Install R from source with Atlas (OpenBLAS doesn't seem to play nice with library(parallel))
RUN wget https://stat.ethz.ch/R/daily/R-devel.tar.gz --no-check-certificate -O /tmp/R.tar.gz -q && \
    tar -xf /tmp/R.tar.gz -C /home/developer && \
    rm /tmp/R.tar.gz && \
    cd /home/developer/R-devel && \
    xvfb-run -a ./configure --with-recommended-packages=no --with-x=yes --with-tcltk --with-aqua --with-ICU --with-cairo --with-libpng --with-libtiff --with-jpeglib --enable-R-shlib --enable-BLAS-shlib --enable-memory-profiling && \  
    xvfb-run -a make && \
    xvfb-run -a make check && \
    xvfb-run -a make install && \
    apt-get install libatlas3gf-base liblapack3gf xclip xsel -y

##Install ggcyto, which needs R-devel to work
RUN wget https://github.com/RGLab/ggcyto/archive/trunk.zip -O /tmp/ggcyto -q && \
    unzip -o /tmp/ggcyto -d /home/developer/ggcyto && \
    echo 'install.packages("/home/developer/ggcyto/ggcyto-trunk", repos = NULL, dependencies = TRUE)' >> /home/developer/packagesSource.R && \
    rm /tmp/ggcyto

##Install H2O
RUN echo 'Installing H2O' && \
    wget http://h2o-release.s3.amazonaws.com/h2o/rel-slater/5/h2o-3.2.0.5.zip -O /tmp/h2o.zip -q && \
    unzip -o /tmp/h2o.zip -d /home/developer && \
    rm -rf /tmp/h2o.zip

##Install flowiQC. Downloading does not always work, so unzip was throwing an error. Unzipping with jar seems to yield no error even for a corrupted file.
RUN wget https://github.com/SIgNBioinfo/flowiQC_shinyAPP/archive/master.zip -O /home/developer/flowiQC.zip -q && \
    jar -xvf /home/developer/flowiQC.zip && \
    rm -rf /home/developer/flowiQC.zip

##Install MSSQL database connector
RUN wget http://www.java2s.com/Code/JarDownload/sqljdbc4/sqljdbc4-3.0.jar.zip -O /home/developer/sqljdbc4.jar.zip -q && \
    jar -xvf /home/developer/sqljdbc4.jar.zip && \
    rm -rf /home/developer/sqljdbc4.jar.zip

##Install Combo
RUN mkdir -p /home/developer/Combo && \
    wget http://senseable.mit.edu/community_detection/combo.zip -O /tmp/combo.zip -q && \
    unzip -o /tmp/combo.zip -d /home/developer/Combo && \
    rm -rf /tmp/combo.zip && \
    echo '#!/bin/bash' > /home/developer/prepend.sh && \
    echo 'content=$(cat /home/developer/Combo/Graph.h)' >> /home/developer/prepend.sh && \
    echo 'echo -en "#include <stdio.h>\n$content" > /home/developer/Combo/Graph.h' >> /home/developer/prepend.sh && \
    chmod 777 /home/developer/prepend.sh && \ 
    /home/developer/prepend.sh && \
    cd /home/developer/Combo && make

##Install SNAP
RUN wget https://github.com/snap-stanford/snap/archive/master.zip -O /tmp/snap.zip -q && \
   unzip -o /tmp/snap.zip -d /home/developer/snap && \
    rm -rf /tmp/snap.zip && \
    cd /home/developer/snap/snap-master && make all

##Install RapidMiner --- SOURCEFORGE LINK BROKEN!!!
RUN wget http://sourceforge.net/projects/rapidminer/files/1.%20RapidMiner/5.3/rapidminer-5.3.013.zip/download -O /tmp/RapidMiner.zip -q && \
    echo 'Installing RapidMiner' && \
    unzip -o /tmp/RapidMiner.zip -d /home/developer && \
    rm -rf /tmp/RapidMiner.zip

##Install MouseImmuneReference
RUN wget https://s3.amazonaws.com/supplemental.cytobank.org/report_data/report_116/mouse_immune_reference_1000.scaffold -O /home/developer/mouse_immune_reference_1000.scaffold -q

##Install Gephi
RUN wget https://launchpad.net/gephi/0.8/0.8.2beta/+download/gephi-0.8.2-beta.tar.gz -O /home/developer/gephi-0.8.2-beta.tar.gz -q && \
    tar -xf /home/developer/gephi-0.8.2-beta.tar.gz -C /home/developer && \
    rm -rf /home/developer/gephi-0.8.2-beta.tar.gz && \
    ##Run Gephi: cd /home/developer/gephi && ./bin/gephi && \

##Install Cytoscape
RUN wget http://chianti.ucsd.edu/cytoscape-3.2.1/cytoscape-3.2.1.tar.gz -O /tmp/cytoscape-3.2.1.tar.gz -q && \
    tar -xf /tmp/cytoscape-3.2.1.tar.gz -C /home/developer && \
    rm /tmp/cytoscape-3.2.1.tar.gz -rf && \
    cd /home/developer/cytoscape-unix-3.2.1 && chmod a+x cytoscape.sh

##Download Cytoscape Plugin ClustnSee - install within Cytoscape
RUN wget http://tagc.univ-mrs.fr/tagc/download/Software/ClustnSee/ClustnSee.jar -O /home/developer/cytoscape-unix-3.2.1/ClustnSee.jar -q


